# Generated by Django 6.0.3 on 2026-03-14 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dentista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("registro", models.CharField(max_length=100, unique=True)),
                ("especialidade", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedimento", models.CharField(max_length=500)),
                ("tempo_estimado", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="AgendaTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("SEG", "Segunda-Feira"),
                            ("TER", "Terça-Feira"),
                            ("QUA", "Quarta-Feira"),
                            ("QUI", "Quinta-Feira"),
                            ("SEX", "Sexta-Feira"),
                            ("SAB", "Sábado"),
                            ("DOM", "Domingo"),
                        ],
                        max_length=3,
                    ),
                ),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField()),
                (
                    "dentista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.dentista",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Agendada", "Agendada"),
                            ("Realizada", "Realizada"),
                            ("Cancelada", "Cancelada"),
                            ("Faltou", "Faltou"),
                        ],
                        default="Agendada",
                        max_length=20,
                    ),
                ),
                (
                    "dentista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.dentista",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.paciente",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clinica.procedimento",
                    ),
                ),
            ],
        ),
    ]
